version: '3.6'

services:
  server:
    image: node
    environment:
      DATABASE_URL: postgres://root:password@db:5432/app
      JWT_SECRET: HhJK7!hjjh!jg2addMJ78bj
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build
